### ISSUE TITLE
Searching always triggers a new tab

### ISSUE THREAD

**Issue by PhyllisJu** [PhyllisJu/todo-tab-react-extension#2]
After submitting the search form, the url is always opened in a new tab, and the extension is refreshed in its own tab.

**Comment by mkmark** [comment]
This has already been fixed [here](https://github.com/PhyllisJu/todo-tab-react-extension/blob/b7776be80e8303f13d54a4e08b5a0a297e1f1297/src/components/SearchBar.js#L45).
